---
# tasks file for start_service
- name: "Start services for {{ host_group_name }}"
  service:
    name: "{{ start_item }}"
    state: started
  with_items: "{{ package_to_start }}"
  loop_control:
    loop_var: start_item
