---
# tasks file for copy_repo
- name: "Set up Repositories"
  template:
    src: "{{ repo_item.source }}"
    dest: "{{ repo_item.dest }}"
    mode: "{{ repo_item.mode }}"
  with_items: "{{ repo_template }}"
  loop_control:
    loop_var: repo_item 
