---
# tasks file for copy_repo
- name: Copy template file for {{ item.source }}
  template:
    src: templates/{{ item.source }}
    dest: {{ item.dest }}
    mode: {{ item.mode }}
  with_items: {{ repo_template }}
  
