---
# tasks file for create_file_or_dir
- name: "create files/directories for {{ host_group_name }}"
  file:
    path: "{{ filedir_item.path }}"
    state: "{{ filedir_item.state }}"
  with_items: "{{ create_file_or_dir_vars }}"
  loop_control:
    loop_var: filedir_item
  
