---
- name: configure common to all
  hosts: all
  gather_facts: true
  become: yes
  tasks:
  - name: Configure Repo
    include_role:
      name: copy_repo

- name: Configure loadbalancer
  hosts: frontends
  become: yes
  tasks:
  - name: Configure haproxy
    include_role:
      name: "{{ item }}"
    with_items: "{{ role_order }}"

- name: Configure App Servers
  hosts: apps
  become: yes
  tasks:
  - name: configure tomcat
    include_role:
      name: "{{ item }}"
    with_items: "{{ role_order }}"


