---
- name: Install package
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ package_to_install }}"
- name: Enable at boot
  service:
    name: "{{ item }}"
    enabled: yes
  with_items: "{{ package_to_install }}"
