---
- name: Install package
  yum:
    name: "{{ install_item }}"
    state: latest
  with_items: "{{ package_to_install }}"
  loop_control:
    loop_var: install_item
- name: Enable at boot
  service:
    name: "{{ enable_item }}"
    enabled: yes
  with_items: "{{ package_to_start }}"
  loop_control:
    loop_var: enable_item
