---
- name: "Install packages for {{ host_group_name }}"
  yum:
    name: "{{ install_item }}"
    state: latest
  with_items: "{{ package_to_install }}"
  loop_control:
    loop_var: install_item
- name: "Enable services at boot for {{ host_group_name }}"
  service:
    name: "{{ enable_item }}"
    enabled: yes
  with_items: "{{ package_to_start }}"
  loop_control:
    loop_var: enable_item
